### ISSUE TITLE
input  format

### ISSUE THREAD

**Issue by MohanaPriyaNarapareddy** [choosehappy/HistoQC#141]
Hello,
I am trying to turn Hiso QC as a service. I created a docker container to run it. Is there any way I could give .svs file in the form of an URL  after instead of mounting the volumes and give it as an argument in the run command. Please let me know.

**Comment by choosehappy** [comment]
interesting question. while something might be able to work, off the top of my head, i don't know of a hosting approach for files which allows for random file read access similar to file systems

if you know of one i can have a deeper think about it, but off the top of my head, the easiest way would be if histoqc took the URL and then downloaded the image locally before proceeding. the libraries employed (openslide) all assume that they'll be able to randomly access parts of the image as needed through file operating system type functions.

seems like that would defeat the purpose of what you're looking for, and would in fact be easier/faster to mount the volumes

**Comment by MohanaPriyaNarapareddy** [comment]
I built a docker container and planning to deploy it in the cloud run. The input files can be hosted in the google cloud bucket and URL can be obtained. But  I am not sure how to provide the URL as the file location in the argument.

**Comment by choosehappy** [comment]
to my knowledge, aws buckets don't allow for random read access, its an all or nothing type approach. thus you'd have to pull it locally to compute on it. you can do so either using wget or "aws s3 cp"

**Comment by sharmaashish** [comment]
Rather than POST the full image, could the requester send the 1.25x magnification image as say a png/jpg?

**Comment by choosehappy** [comment]
one of the issues with that will be that the user can customize the pipeline as they see fit. each module supports a different operating magnification. for example, the blurriness detector works better at 5x if i remember correctly. thus one would likely need to send multiple versions of the same file (or the maximal magnification used by their configuration), and then write code to compensate for that. note as well the backend is using openslide natively, and assumes magnification information will be provided by metadata. to explicitly state magnification and circumvent openslide (since it can't open "flat" png files) is certainly possible, but isn't a 1 minute type fix

**Comment by choosehappy** [comment]
closed due to inactivity
