### ISSUE TITLE
Add support for bioformats?

### ISSUE THREAD

**Issue by choosehappy** [choosehappy/HistoQC#142]
Should look into extending support to bioformats given the end-of-life of openslide

https://pythonhosted.org/python-bioformats/

Issues will be that the dependencies skyrocket as bioformats is java, and thus will require a JVM

Computation time will likely go up as well, limiting throughput

**Comment by jjhbw** [comment]
Out of interest, I have indeed noticed that OpenSlide is not really maintained anymore. Have you encountered any issues with that, though? Do the slide formats that it covers change often enough that the lack of continued maintenance of OpenSlide is an issue?

Bioformats also looks like an amazing lib, but its dependence on the JVM is a worry. Most of the slide-related tooling is hard enough to set up as it is. I must admit i'm not familiar with the latest generation of JVM tooling that may make it more portable to set up, so it may have improved since i last touched the ecosystem.

**Comment by choosehappy** [comment]
thanks for your question

openslide does have its limitations, but the older file formats (svs, ndpi,
big-tiff) have remained the same and we haven't encountered any issues.

the problem is really in the newer file formats, e.g., philips, some of the
newer 3dhistec versions, and of course the less popular scanners are not
supported and unfortunately won't be supported by openslide unless someone
picks up the reins

ultimately, updating openslide is extremely challenging, since many of the
file formats are proprietary, and previously had to be reverse engineered
for openslide, not an easy or forgiving task

we've also considered bioformats, but your concerns are warranted. it is
quite "heavy" dependency wise, the integration with python is complex, and
the overall computation time to read the slides is slower than that of
openslide. we're certainly interested in offering that as an option if
openslide is not able to read a slide, but it would involve quite a bit of
effort to support both simultaneously.

keep in mind as well, that most researchers like ourselves, have A LOT of
legacy code built up over the last decades which use older libraries (e.g.,
openslide), so without strong motivation to redevelop the wheel with a new
library, there will be some blindspots in implementations.

hopefully as digital pathology becomes more popular, standards will be
introduced, and common file formats will be created, and then a singular
high-speed library will be created for reading them,but i fear that time is
still quite far off

**Comment by jjhbw** [comment]
Interesting. I'm new to digital pathology and am trying to get an idea of the state of the ecosystem, so your comment is very useful. Thanks!
