### ISSUE TITLE
Thumbnails not loading in UserInterface

### ISSUE THREAD

**Issue by yau-lim** [choosehappy/HistoQC#147]
Hello,

Thank you for developing this very useful tool!

While trying to view my results in the user interface, the thumbnails would not load. I tried opening the index.html in Chrome and Firefox and neither worked. The thumbnails are present in the output folders.

I suspect it might be due to filepath issues; I used HistoQC in Windows Subsystem for Linux as there were issues with Visual C++ 14.0 and Python3 in Python for Windows.

I tried changing the filepath format to the Windows format in results.tsv but that did not help.

Are there any other configuration files that I need to adapt for HistoQC to be able to load thumbnails generated from WSL?

Many thanks,
Yau

**Comment by choosehappy** [comment]
I often run HistoQC in linux environments and copy over the results for
viewing in Windows environments

So there shouldn't be anything *inherently *problematic

Some issues which sometimes arise are spaces in file or pathnames, which
we've made efforts to try and correct, but sometimes miss some places

I would suggest looking at the google chrome javascript console (ctrl +
shift + j  will launch it directly), and then reload the page

If the thumbnails are not showing up, there will be a long list of error
messages, clicking on any of them will tell you where it "tried" to load
the image from. Compare that with the location where the files actually
"are", and that will help figure out where the issue is

Does that make sense?

**Comment by yau-lim** [comment]
Thanks for your reply! 

It tries to load the image from HistoQC/UserInterface/Data/ but the images were exported into the results folder in the base folder HistoQC/histoqc_output.

HistoQC/UserInterface/Data only has empty (0 b) files with the results' folder names.

How can change the directory in which the index.html finds the images?

**Comment by choosehappy** [comment]
since we're not using a webserver of any sort, all files need to be
relative to the UserInterface directory

on linux you can use a softlink (which histoqc pipeline does try to make on
its own), on windows you can manually move the data there

Once its matched up, it'll pop up

**Comment by yau-lim** [comment]
It works when I moved the data to ./UserInterface/Data

Thanks for your help!

**Comment by choosehappy** [comment]
perfect, thanks for reporting back and closing the ticket!

**Comment by ljimenez93** [comment]
I'm getting the same issue. Can you tell me what data exactly did you move to ./UserInterface/Data?
I'm on Windows 10. Tried loading the results in Edge and Chrome and same error.

**Comment by jacksonjacobs1** [comment]
Hi @ljimenez93, 

@yau-lim solved this problem by moving each of the image folders to ./UserInterface/Data:

UserInterface
|_ Data
|   |_ image1
|   |   |_ thumbnail1.png
|   |   ...
|   |_image2
|   ...
|   results.tsv

Since results.tsv is included in the histoQC output, I've included it in the file structure. However, histoqc.ui will use the results file uploaded via the front-end. Does that make sense?

**Comment by yau-lim** [comment]
Thanks @jacksonjacobs1. It's been awhile since I've used HistoQC, so I could not remember exactly what I did to solve the issue.

**Comment by choosehappy** [comment]
Can we add this information to the documentation somewhere? I gues sin the readme would be most appropriate so its easily found?
________________________________
From: yau-lim ***@***.***>
Sent: Monday, November 27, 2023 3:53 PM
To: choosehappy/HistoQC ***@***.***>
Cc: Janowczyk, Andrew R. ***@***.***>; Comment ***@***.***>
Subject: [External] Re: [choosehappy/HistoQC] Thumbnails not loading in UserInterface (#147)


Thanks @jacksonjacobs1<https://github.com/jacksonjacobs1>. It's been awhile since I've used HistoQC, so I could not remember exactly what I did to solve the issue.

**Comment by jacksonjacobs1** [comment]
PR #273 adds troubleshooting section to address this problem.

**Comment by ljimenez93** [comment]
Hey @jacksonjacobs1 
Thanks for your reply. I've been a little busy but today I tried your solution and still doesn't work for me. I'll dig into the problem. If I find something I'm going to edit this comment. Thank you all

**Comment by yau-lim** [comment]
I have tried using HistoQC on Windows again and I echo @ljimenez93 's findings that the solution no longer works.

In the console after running histoqc.ui, I saw this:
```
"GET /Data//image.svs/image.svs_thumb_small.png HTTP/1.1" 404 -
```
Could it be that the `//` is causing the issue? That the path is invalid?

**Comment by yau-lim** [comment]
An update after some investigation:

Assuming the data folders are moved to `./UserInterface/Data` as mentioned by @jacksonjacobs1 above,

The thumbnails failed to load when using HistoQC UI following the command `python -m histoqc.ui` and launching `localhost:8000` in the browser.

However, if I directly open `index.html` from `HistoQC/histoqc/ui/UserInterface` into a browser (which I believe was the old way to do it), the thumbnails do load.

Is there anything further that I can do to help troubleshoot the issue?

**Comment by choosehappy** [comment]
what is the exact command you're using and associated directory structure?

basically if i have an output directory like this: C:\research\camelyon17\histoqc_output

which contains within it the results.tsv and the associated subdirectories for each output file, i can run histoqc UI like this:


```bash
python -m histoqc.ui C:\research\camelyon17\histoqc_output
```

and it works without a problem

**Comment by ljimenez93** [comment]
I also noticed the `//` in the path as @yau-lim did. But none of the previous solutions worked for me.

**Comment by choosehappy** [comment]
duplicated // are merged together in modern operating systems, so very likely not related here, for example:

![image](https://github.com/choosehappy/HistoQC/assets/9681868/7746f3b6-4e6e-41a2-8c9f-a90b157213a2)

 works without issue. this is especially true for HTTP protocols

i think we'll need more information to debug, including tobegin with

a) command run
b) directory from which the command was run
c) directory structure of the associated results

**Comment by yau-lim** [comment]
> what is the exact command you're using and associated directory structure?
> 
> basically if i have an output directory like this: C:\research\camelyon17\histoqc_output
> 
> which contains within it the results.tsv and the associated subdirectories for each output file, i can run histoqc UI like this:
> 
> ```shell
> python -m histoqc.ui C:\research\camelyon17\histoqc_output
> ```
> 
> and it works without a problem

My HistoQC folder path is effectively `C:\yau-lim\HistoQC`, in which contains all the HistoQC files as installed according to your instructions. This folder is also the default for the output folders with the preset folder names `histoqc_output_yyyymmdd-hhmmss`.

From your suggestion on specifying a folder path while launching `histoqc.ui`, I tested the following:

```
python -m histoqc.ui
```
Thumbnails do not load upon choosing results.tsv in any of the histoqc_output folders.

```
python -m histoqc.ui "C:\yau-lim\HistoQC"
```
Thumbnails still do not load when specifying the parent HistoQC folder which contains the histoqc_output folders.

```
python -m histoqc.ui "C:\yau-lim\HistoQC\histoqc_output_yyyymmdd-hhmmss"
```
Specifying any of the histoqc_output folders results in thumbnails loading, even if the results.tsv are from another histoqc_output folder under `C:\yau-lim\HistoQC`.

Being able to specify a folder when launching `histoqc.ui` is not apparent from the readme, so perhaps this can be mentioned.

![image](https://github.com/choosehappy/HistoQC/assets/57093006/d47bf5e6-7318-4e7d-a0f9-23a0eec5cc22)

**Comment by jacksonjacobs1** [comment]
Hi @yau-lim, thank your for your points. The third command you used...
```
python -m histoqc.ui "C:\yau-lim\HistoQC\histoqc_output_yyyymmdd-hhmmss"
```

... is the correct format for specifying the HistoQC output directory. Alternatively, you can change your current working directory to the histoqc output directory and run the following command:
```
python -m histoqc.ui
```

That's because histoqc.ui uses the current working directory as the data directory by default:
https://github.com/choosehappy/HistoQC/blob/79943ccd8f07e9b9a75460866a1f43a10d616c34/histoqc/ui/__main__.py#L21

The current documentation does not make this clear, so I'll publish a commit shortly to improve the documentation.

Please let me know if you have any additional questions.

**Comment by jacksonjacobs1** [comment]
Hi all, the readme was updated to document this behavior in #273.

The information was added to the following section of the readme:
https://github.com/choosehappy/HistoQC?tab=readme-ov-file#histoqcui-cli

**Comment by yau-lim** [comment]
Thanks @jacksonjacobs1, this definitely improves the clarity on the usage of histoqc.ui. However, I can't help but think why is the default data directory for histoqc.ui not relative to the results.tsv? 

The necessary thumbnail images for each results.tsv is the in the same output folder as the tsv itself, so shouldn't it make sense for histoqc.ui to find the thumbnails in the same folder as the selected results.tsv?

**Comment by choosehappy** [comment]
when uploading the results.tsv file in the front end, the directory its coming from is obscured by modern web browsers for security: https://stackoverflow.com/questions/15201071/how-to-get-full-path-of-selected-file-on-change-of-input-type-file-using-jav

so we have no way of knowing which directory the results.tsv resides in. we store this information in the header, but many people (myself included), run histoqc on a server and then copy the results locally, so the header information is no longer accurate in that case either

**Comment by yau-lim** [comment]
I see, that makes sense. With that, I think this issue is resolved for now and I will close it. Many thanks for the help @choosehappy @jacksonjacobs1 !
