### ISSUE TITLE
Manually specify base magnification

### ISSUE THREAD

**Issue by ellenemerson** [choosehappy/HistoQC#150]
Hello,

I am trying to use this package on generic BigTiff files for which no magnification metadata is included.  Out of the box, the qc pipeline won't finish because a magnification value is required for the analysis.  I was able to get it to work by hard coding the magnification value in BaseImage.py, but I was wondering if there is a better way (through the config file for example) to manually specify the base magnification?

Thanks!
Ellen

**Comment by choosehappy** [comment]
thanks for reaching out

currently your approach is the best way to deal with this issue

we've been thinking about other ways, but the issue is is that this may
actually do damage in many experiments. for example, the TCGA has images at
both 20x and 40x (many people do not realize), and i suspect this may be
the case for other diverse cohorts.

the problem is thus 2 fold, if there are different magnifications and the
person is unaware: (a) histoqc won't function properly or consistently as
it will would create different pseudo magnifications and the
filters/modules won't produce consistent results and (b) i think we're
failing as a QC program if we enable people to circumvent the check for
this type of problem given how severe i think it is

the way we would like to address it going forward is to automatically
detect the appropriate magnification, and confirming it against the
metadata (if available), but this remains challenging to develop an
algorithm to do this for all tissue types across all scanners with many
different possible stains

if you have any ideas, i would be very happy to hear them

cheers,
andrew
