### ISSUE TITLE
Failed to allocate memory for to read TIFF directory

### ISSUE THREAD

**Issue by petrovm3** [choosehappy/HistoQC#153]
I don't know how to interpret the following INFO message:

```
INFO - -----Working on: /path_to_Aperio_file/blabla.svs 27 of 61
/path_to_Aperio_file/blabla.svs: Failed to allocate memory for to read TIFF directory (0 elements of 12 bytes each).
TIFFReadDirectory: Failed to read directory at offset 719387610.
```

I am processing an Aperio svs file and I see a message related to a TIFF file. Is there an error in the Aperio file? Is it an error or only an information ?

**Comment by choosehappy** [comment]
This image wasn't created correctly:

![image](https://user-images.githubusercontent.com/9681868/75372125-4571a280-58c8-11ea-9fdf-eb225387ffb2.png)

There is only a single very very large level in the pyramid (image above created using imagescope)

HistoQC+ openslide try to make the best of it, but it will try to make an image of size 76k * 42k * 3 == 9.5GB, and this ultimately why it fails

the underlying error is actually from libtiff, as it can't create an image this large

**Comment by choosehappy** [comment]
I suspect this image is corrupt, is that a possiblity? 

this component seems to work correctly:

https://github.com/choosehappy/HistoQC/blob/ca7c9edb6c025de9f4716dc5c3b5fb75d048a10c/BaseImage.py#L108

but note it will take a very long time to complete, as it will load each tile of the 40x version and resize it down to 1.5x

that said, it does eventually break but as i mentioned it looks to be as a result of trying to read a part of the image which doesn't actually exist in the file, likely due to corruption. 

not much we can do here
