### ISSUE TITLE
Documentation for module function and parameters

### ISSUE THREAD

**Issue by asmagen** [choosehappy/HistoQC#164]
Where can I see the definition and list of parameters and value ranges for each module/function?
For example, what is detectSmoothness and how can I adjust it?

**Comment by choosehappy** [comment]
list of modules is here:

https://github.com/choosehappy/HistoQC/wiki

 the base config.ini has a list of every possible parameter. they should
hopefully be self explanatory.

all thresholds are from [0,1]

**Comment by asmagen** [comment]
Thanks. Some of them are but some aren't. For example, what are the parameters here?
[BubbleRegionByRegion.detectSmoothness]
threshold: .01
kernel_size: 10
min_object_size: 500

**Comment by choosehappy** [comment]
thank you for your question

our target users are expected to have minimal image processing experience
in order to use this tool. documentation to this extent will
unfortunately not be possible given our resources

that said, each module was written in a way that the usage of the
particular parameters should be obvious. in this case the core of the
detectSmoothness module consists of only 6 lines, hopefully compact and
pythonic enough to be easily digestible by modestly experienced users but
certainly within the realm of stepping through with a debugger for complete
lay folks

in this case:

we create an average filter (defined by kernel size)
        avg = np.ones((kernel_size, kernel_size)) / (kernel_size**2)
convolute with the input image

        imf = scipy.signal.convolve2d(img, avg, mode="same")

and threshold it based on the threshold filter
        mask_flat = abs(imf - img) < thresh

finally cleaning up the image by removing any small objects using the min
object size parameter:

        mask_flat = remove_small_objects(mask_flat,
min_size=min_object_size)
        mask_flat = ~remove_small_objects(~mask_flat,
min_size=min_object_size)
