### ISSUE TITLE
Classification module

### ISSUE THREAD

**Issue by asmagen** [choosehappy/HistoQC#168]
How does the ClassificationModule work? "Applies an RGB based classifier to the image whose values come from a user inputed TSV". What is that TSV and how do you recommend to construct it?

Thanks

**Comment by choosehappy** [comment]
This is used for identifying pixels of specific values using a naive
gaussian classifier. one can provide RGB values of pixels of interest
(label = 1) versus non-pixels of interest (label=0)

Initially this was used to identify pen-markings, but we later found that
the classifier by example with features approach was more beneficial as it
was more robust (though more computationally expensive)

there are 5 lines needed to understand it:

we load a tab seperated file, and skip the top row under the assumption the
user has placed a header there
    model_vals = np.loadtxt(fname, delimiter="\t", skiprows=1)

Create a naive bayes classifier
    gnb = GaussianNB()

train it pre-derived RGB values from the file and the label
    gnb.fit(model_vals[:, 1:], model_vals[:, 0])

apply it to the image
    cal = gnb.predict_proba(img.reshape(-1, 3))

threshold the resulting probability to identify the positive class
    mask = cal[:, :, 1] > thresh

**Comment by asmagen** [comment]
Thanks. So model_vals[:, 1:] is an RGB vector corresponding to the positives while model_vals[:, 2:] is RGB corresponding to negatives?

Do you have any advice about strategies/tools for finding the right thresholds for the red pixels in the following snippet image for example? 
<img width="412" alt="Screen Shot 2020-03-22 at 11 08 10 PM" src="https://user-images.githubusercontent.com/11299568/77326250-ea2ca780-6cef-11ea-9ad8-b42cada75c83.png">

**Comment by choosehappy** [comment]
Not quite

it would look like:
label R1 G1 B1
label R2 G2 B2
label R3 G3 B3

where label \in {0,1}

#---
These look like IHC stained images, and it sounds like you're trying to
quantify their intensity + extent.

I would not use HistoQC for this purpose, as this is a whole area of
research on its own and is non-trivial to do robustly across multiple
images using singular non-dynamic thresholds.

Instead you can use some existing tools, such as QuPath and ImageJ/Fiji

**Comment by asmagen** [comment]
I see. But QuPath/ImageJ or GUI based and don't scale nicely to large whole slide pathology images, which is why I was looking for a python based package to assist with that in a server based setting rather than personal computer app with GUI. Do you know of anything like that?

**Comment by choosehappy** [comment]
hmm sorry i don't think i know of any publicly available ones. from my
experience people typically end up making their own approach since their
localization requirements tend to be unique

for example, folks often want to identify expression in relation to
specific cells or structures, and thus also need to segment these items
(e.g., cells).

The issue then becomes finding a robust cell-segmenter which works for
their tissue / stain / scanner combination (DL is not yet very robust in
this regard), so by time they finish developing that component from
available code (some examples on my blog) the infrastructure is in place to
perform IHC quantification using their favorite approach/latest
algorithm/clustering etc. its not too difficult to develop something once
you have a homogenous dataset. HistoQC struggles because we cannot make
assumptions about tissue or stain type, preventing a lot of "easy wins"

Note that this is only in the case of 1000ss of slides. For smaller sets,
people use FIJI (which has some IHC toolboxes) + QuPath, both of which have
"compute on batches of slides options" which can apply a pipeline to a
series of WSI images, which is usually sufficient for 10s of images

if you happen to find something suitable for your needs, i would love to
hear about it!
