### ISSUE TITLE
Function of DeconvolutionModule.seperateStains

### ISSUE THREAD

**Issue by asmagen** [choosehappy/HistoQC#169]
Can you clarify the function and usage of DeconvolutionModule.seperateStains?
I have a Hematoxylin + AEC staining from which I would like to obtain an image representing only the AEC with the appropriate mask. Or does this module work to deconvolute the stains just for the mask definition without an option to obtain a deconvoluted image?
```
[DeconvolutionModule.seperateStains]
;hed_from_rgb: Hematoxylin + Eosin + DAB
;hdx_from_rgb: Hematoxylin + DAB
;fgx_from_rgb: Feulgen + Light Green
;bex_from_rgb: Giemsa stain : Methyl Blue + Eosin
;rbd_from_rgb: FastRed + FastBlue + DAB
;gdx_from_rgb: Methyl Green + DAB
;hax_from_rgb: Hematoxylin + AEC
;bro_from_rgb: Blue matrix Anilline Blue + Red matrix Azocarmine + Orange matrix Orange-G
;bpx_from_rgb: Methyl Blue + Ponceau Fuchsin
;ahx_from_rgb: Alcian Blue + Hematoxylin
;hpx_from_rgb: Hematoxylin + PAS
stain: hed_from_rgb
use_mask: True

```

**Comment by choosehappy** [comment]
this module is very limited.

we basically provide support for running this:

https://scikit-image.org/docs/dev/auto_examples/color_exposure/plot_ihc_color_separation.html


within the workflow. we save those images, and report the mean and standard
deviation values. this is mostly a useful metric when looking at things at
a cohort level, to identify any slides which may be over/under stained
versus their counterparts

This module does not affect the output mask

**Comment by asmagen** [comment]
So I ran this scikit tutorial and got the following results which were a bit concerning given the background color in each image, unlike the black color in the overlay presented in the tutorial. Is it possible that the deconvolution couldn't separate the colors well? Is there a way to account for that?
<img width="1383" alt="Screen Shot 2020-03-26 at 10 23 02 AM" src="https://user-images.githubusercontent.com/11299568/77660540-d54e4f00-6f4f-11ea-9e27-3d8e70caa70c.png">
<img width="382" alt="Screen Shot 2020-03-26 at 10 29 40 AM" src="https://user-images.githubusercontent.com/11299568/77660544-d67f7c00-6f4f-11ea-9dc8-c6fdba65b17a.png">

**Comment by choosehappy** [comment]
this looks correct to me


a few points:
1) hed is H&E with DAB, the DAB is assumed to be brown, while yours is red,
this is likely going to cause some errors
2) if you read how the stain deconvolution algorithm works, you'll see that
it depends *very* heavily on having an appropriate stain matrix

unfortunately, since slides and preparations vary highly between
institutions, the optimal matrix used for one slide is likely not the same
for another slide

The help with this issue, the authors suggested staining "bare" slides with
each stain to determine the relative contribution. this in practice is no
possible, but may be doable in your facility

you can read their paper here:
https://s3.amazonaws.com/academia.edu.documents/40705455/AnalQuantCytHist-AR.pdf


3) that said, there are ways to estimate a better matrix, QuPath has some
functionality built-in for that. once you know your ideal matrix or for
example: https://geertlitjens.nl/publication/geij-18/geij-18.pdf

once you have the stain matrix, more approaches will let you provide it
directly to the algorithm in place of the ones that they're proposing for
usage

for skiamge you can use "separate_stains(rgb, conv_matrix):" and provide
the matrix there

**Comment by asmagen** [comment]
Thank you!
