### ISSUE TITLE
HistoQC UI : extending the set of possible image format identifiers defined in global_config.js

### ISSUE THREAD

**Issue by petrovm3** [choosehappy/HistoQC#170]
We have implement a new method scoring the blurriness. It generates as well a _blurry.png file but we want to compare it with the default one from HistoQC for comparing both algorithm results (ski-image vs openCV) 

The comparison will be visual using the HistoQC UI.
Currently to do this, we had to extend the global_config.js source code as following:

/****************** IMAGE VIEW ****************/
// full set of possible image format identifiers. 
var DEFAULT_IMAGE_EXTENSIONS = [
   ...
   "_blurry.png",
   "_blurry_MY_SPECIFIC_RESULT.png",
   ...
];

It would be nice to list all default image extensions in the config.ini file.
HistoQC UI will then dynamically read them from there.

Would it be please, possible to extend the UI logic to do that?

**Comment by choosehappy** [comment]
unfortunately, this is a technical limitation imposed by web browsers and
our decision to not use a local web server to provide the pages

for safety reasons the browser only allows the UI html page to have access
to itself and subdirectories, never parent directories

for the same reason the output directories need to be either soft links or
physically copied into the Data directory in the UI

that said, if you plan on programmatically modifying the results frequency,
at the end of the python component you can have code which modifies the JS,
since there is no file access limitation from that side

**Comment by petrovm3** [comment]
Thanks for your feedback. In deed this is what we did by extending our specific Dockerfile using the COPY command for copying our adapted global_config java script.
