### ISSUE TITLE
tips for visualizing QC results on a large dataset?

### ISSUE THREAD

**Issue by kaczmarj** [choosehappy/HistoQC#199]
I'm so happy to have found HistoQC -- thank you very much for developing and maintaining this project. I am working with a dataset of about 32,000 whole slide images. I ran histoqc on all of the slides with the `config_first.ini` configuration. That ran well and finished in less than 24 hours. Now I am attempting to visualize the results with `histoqc.ui`, and the browser page is taking a very long time to load. To be honest, I never got to see the results in the HTML page because the load time was so long. It's made worse because the histoqc outputs exist on a remote server, and the outputs are about 179GB in size.

I was wondering how I could change the UI or the `results.tsv` file to only show the information I want. 

- Let's say I only want to see the parallel plot (the high-dimensional data plot). How could I go about that? Would it involve only a change to `results.tsv`?
- I also considered chunking the `results.tsv` file to 1,000-file  chunks. I chose not to do this because I wouldn't be able to see the variation across the entire dataset.
- Is it possible to disable loading of some images? I _think_ (but definitely don't know for certain) that the number of images is the bottleneck. Could I ask the UI to only show, for example, the tissue thumbnail + the final tissue mask?

**Comment by kaczmarj** [comment]
the html UI loaded up, but it causes my browser to become unresponsive. i'd really appreciate any tips for visualizing the qc results.

**Comment by kaczmarj** [comment]
to visualize the parallel coordinates plot, i ended up using hiplot (https://facebookresearch.github.io/hiplot/). looks good so far. here's how i did it... this uses the `results.tsv` file from histoqc.

```python
# pip install hiplot pandas
import io
import hiplot as hip
import pandas as pd

# workaround to extract column names.
with open("results.tsv") as f:
    results = f.read().strip()
results = results.replace("#dataset:", "")
df = pd.read_csv(io.StringIO(results), sep="\t", comment="#")
del results

exp = hip.Experiment.from_dataframe(df)
_ = exp.to_html("index.html")
```

then i started a webserver in the directory that contains `index.html` ...

```bash
python3 -m http.server
```

and navigate to http://0.0.0.0:8000 in a browser.

**Comment by choosehappy** [comment]
Thanks for your questions! You hit it exactly on the head, the images are the main bottleneck here

The main way I've dealt with this before is to use:

  -b BATCH, --batch BATCH, break results file into subsets of this size

and set it to around 1,000. This organically breaks up the results.tsv into results_1.tsv, results_2.tsv, etc

So that upon loading each results file individually, it can stay within the memory constraints of the browser. I appreciate this isn't ideal since you only end up seeing 1k slides at a time, but it was a sufficiently quick fix for the datasets we had which max out around 2k

Your situation is obviously more challenging, and in fact we've already discussed possible solutions with @foggydae , the developer of the user interface and they are in progress:

Now that the new version of HistoQC has a "proper" web-server backend, it will be much easier to load images on-demand using pagination, to limit the overall load time, memory, and network constraints.

Would something like that be suitable in your case as well?

As a shorter term fix, we could simply disable loading images if there are >1000, I think the rest of the UI would still work as expected (table + parallel cooridnate plot)

This HiPlot code is pretty cool as well, but I'm having difficulty in being able to see all the column names, I've dug up an issue over there and suggested a solution ( https://github.com/facebookresearch/hiplot/issues/147 )

**Comment by kaczmarj** [comment]
@choosehappy - my apologies for the late reply. i'm using histoqc now on a relatively large dataset and it's working great. i'll close this issue. thanks again for your help!!

**Comment by choosehappy** [comment]
perfect, thanks for getting back to me!
