### ISSUE TITLE
Unknown base magnification for file

### ISSUE THREAD

**Issue by nicitamehta** [choosehappy/HistoQC#212]
Hi,

This may be related to [#159](https://github.com/choosehappy/HistoQC/issues/159) and [#206](https://github.com/choosehappy/HistoQC/issues/206), but I am trying to qc IHC images in svs format and am running into the error pictured below. Any help would be greatly appreciated! 

<img width="1376" alt="Screen Shot 2022-01-04 at 16 47 40" src="https://user-images.githubusercontent.com/71670473/148128273-496d3db8-c4e5-4092-b51e-f12e60372a78.png">

**Comment by choosehappy** [comment]
Very interesting, what type of scanner made the SVS file but didn't include the magnification in the header?

Quite strange

Anyway, you have two options, you can either explicitly set the base magnification in histoqc here:

https://github.com/choosehappy/HistoQC/blob/9c15c1767de0a9d1d54fa87b3e819a225b0fad00/histoqc/BaseImage.py#L31

with a return statement like "return 40.0" if your mag is 40x

or you can use this approach to add the same information to your svs files:

http://www.andrewjanowczyk.com/converting-an-existing-image-into-an-openslide-compatible-format/

The latter might be more appropriate, since afterwards they will be usable by "all" digital pathology tools

**Comment by nicitamehta** [comment]
thank you for the quick reply! for context, these were previously .scn files scanned on a Leica Versa that were converted to .svs format. I still seem to be running into the same issue (see pic for the changes made). I've also tried to hardcode the mag in line 67 of the same script. any other recommendations? thank you again!

![image](https://user-images.githubusercontent.com/71670473/148290690-16db548d-995c-461e-b836-acbdbffe1b43.png)

**Comment by choosehappy** [comment]
Hmmm...What does the output/error look like?

**Comment by nicitamehta** [comment]
![image](https://user-images.githubusercontent.com/71670473/148402180-7e99a6d2-322a-4e59-92e1-09c97d8eae81.png)

**Comment by choosehappy** [comment]
Sorry to be blunt, but this output should be impossible if you've made the changes you described : ) 

As you can see, the phrase "Unknown base" only appears twice within the entire repository:

```
andrew@mindvalley-VII:/mnt/d/temp/HistoQC$ grep -R "Unknown base" *
histoqc/BaseImage.py:        logging.warning(f"{s['filename']} - Unknown base magnification for file")
histoqc/BaseImage.py:        s["warnings"].append(f"{s['filename']} - Unknown base magnification for file")
Binary file histoqc/__pycache__/BaseImage.cpython-37.pyc matches
andrew@mindvalley-VII:/mnt/d/temp/HistoQC$
```

And these are exactly the two lines that you've commented out, and *yet* still appear in your new output as the second line, which should be an impossibility

Can you speculate on why that might be? Unforunately, I'm not really sure what to suggest beyond e.g., deleting the repo, re-cloning, making the same changes, and trying again :-\

**Comment by nicitamehta** [comment]
i ended up remaking my conda env and, with the changes you initially recommended, that worked ¯\_(ツ)_/¯ ! thank you for all your help!

**Comment by choosehappy** [comment]
Great!
