### ISSUE TITLE
"View Results" button in UI creates problems when using port forwarding

### ISSUE THREAD

**Issue by ant0nsc** [choosehappy/HistoQC#224]
I'm running the core HistoQC tool in a large VM in the cloud. When I now want to view the results with `histoqc.ui`, I'm in a bit of trouble:  I can't run the UI directly on the VM, so I need to use port forwarding to my laptop. When I now click the "View results" button, it would open a file dialog on my laptop - but of course my results still live in my cloud VM.

I can copy the `results.tsv` file to my laptop, but that of course makes the workflow more cumbersome.

Do you have any suggestions how we can better proceed? How could we add a way of bypassing that "View Results" button and provide a result file on the commandline, for example? This would cover a lot of our `histoQC` usecases already.

@harshita-s FYI

**Comment by choosehappy** [comment]
Thanks for your question!

To begin, i'll say that we just received additional funding with the intent of scaling up the histotools suite (histoqc.com, patchsorter.com, quickannotator.com, cohortfinder.com)  to function at massive scales

As such, your feedback is very useful and insightful for the types of things that we should be considering

Okay! moving on

I very much understand the problem you're having

The underlying problem here is that we didn't previously have access to the server directory structure because the UI used to be a separate static HTML page.

in this latest version, we've created the wrapped HTTP server that you're seeing. i think this opens up some opportunities for us to more elegantly solve the problem

We have a command line option here for data directory:

https://github.com/choosehappy/HistoQC/blob/7d11503717847edfb7d3db7c8a90556b5bfc544e/histoqc/ui/__main__.py#L19

i assume you're pointing this at your data, and inside of that folder is as well the results.tsv? 

so if we added a command line option to specify a results.tsv filename, the UI could automatically load it.

Is that along the lines of what you were thinking of?

**Comment by ant0nsc** [comment]
Yes, that's what I was thinking about. I actually had a go at that idea yesterday - it took me some time to wrap my head around it because I've never done HTML+JS before, but I have a basic version running. I can create a PR, and would appreciate your input - quite likely I have not chosen the most elegant solution.

**Comment by ant0nsc** [comment]
Added PR #225 @choosehappy FYI
