### ISSUE TITLE
saveMacro Can't Read 'macro' Image from Slide's Associated Images

### ISSUE THREAD

**Issue by Ahmed-khaled12** [choosehappy/HistoQC#253]
I'll attach the google drive link containing the result.tsv file:
https://drive.google.com/drive/folders/1-GRsNx8dGXBlwm6CFGLbvLXATv7wcbU4?usp=share_link

**Comment by nanli-emory** [comment]
Hi @Ahmed-khaled12,
As I understand, the error message indicates that the **1.mrxs** and **2.mrxs** have no **macro** image in the slide's Associated Images because not every WSI has a **macro** image. 
There is the code to read an image from Slide's Associated Images: https://github.com/choosehappy/HistoQC/blob/master/histoqc/SaveModule.py#L43
Please make sure your **1.mrxs** and **2.mrxs** have the marco image inside of them.

Thanks

**CMU-1.mrxs** as a example data that has the **marco**, **label**, and **thumbnail** images in the slide's Associated Images.
**CMU-1.mrxs** data link: https://openslide.cs.cmu.edu/download/openslide-testdata/Mirax/CMU-1.zip
